# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.23
# 
# >> macros
# << macros

Name:       polkit
Summary:    PolicyKit Authorization Framework
Version:    0.104
Release:    1
Group:      System/Libraries
License:    LGPLv2+
URL:        http://www.freedesktop.org/wiki/Software/PolicyKit
Source0:    http://hal.freedesktop.org/releases/%{name}-%{version}.tar.gz
Source100:  polkit.yaml
Requires:   dbus
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(glib-2.0)
BuildRequires:  pkgconfig(libsystemd-login)
BuildRequires:  expat-devel
BuildRequires:  pam-devel
BuildRequires:  intltool


%description
PolicyKit is a toolkit for defining and handling authorizations.
It is used for allowing unprivileged processes to speak to privileged
processes.



%package devel
Summary:    Development files for PolicyKit
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires:   %name = %{version}-%{release}
Requires:   pkgconfig
Requires:   glib2-devel

%description devel
Development files for PolicyKit.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static \
    --disable-gtk-doc \
    --libexecdir=%{_libexecdir}/polkit-1 \
    --disable-introspection \
    --enable-systemd=yes

make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post
%find_lang polkit-1



%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig





%files -f polkit-1.lang
%defattr(-,root,root,-)
# >> files
%doc COPYING
%{_libdir}/lib*.so.*
%dir %{_libdir}/polkit-1
%dir %{_libdir}/polkit-1/extensions
%{_libdir}/polkit-1/extensions/*.so
%{_datadir}/dbus-1/system-services/*
%dir %{_datadir}/polkit-1/
%dir %{_datadir}/polkit-1/actions
%{_datadir}/polkit-1/actions/org.freedesktop.policykit.policy
%config %{_sysconfdir}/dbus-1/system.d/org.freedesktop.PolicyKit1.conf
%config %{_sysconfdir}/pam.d/polkit-1
%config %{_sysconfdir}/polkit-1
%{_bindir}/*
%{_libexecdir}/polkit-1/polkitd
# see upstream docs for why these permissions are necessary
%attr(4755,root,root) %{_bindir}/pkexec
%attr(4755,root,root) %{_libexecdir}/polkit-1/polkit-agent-helper-1
%attr(0700,root,root) %dir %{_localstatedir}/lib/polkit-1/
%dir %{_localstatedir}/lib/polkit-1/localauthority
%dir %{_localstatedir}/lib/polkit-1/localauthority/10-vendor.d
%dir %{_localstatedir}/lib/polkit-1/localauthority/20-org.d
%dir %{_localstatedir}/lib/polkit-1/localauthority/30-site.d
%dir %{_localstatedir}/lib/polkit-1/localauthority/50-local.d
%dir %{_localstatedir}/lib/polkit-1/localauthority/90-mandatory.d
# << files


%files devel
%defattr(-,root,root,-)
# >> files devel
%{_libdir}/lib*.so
%{_libdir}/pkgconfig/*.pc
%{_includedir}/*
%{_bindir}/pk-example-frobnicate
%{_datadir}/polkit-1/actions/org.freedesktop.policykit.examples.pkexec.policy
# << files devel

